# Generated by Django 4.2.7 on 2023-12-04 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publish_time']},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='published_time',
            new_name='publish_time',
        ),
    ]
